# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TractorRisk
                                 A QGIS plugin
 Zoning of tractor rollover risk based on CoG dimensions and terrain.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-23
        copyright            : (C) 2026 by Jeison Bogota
        email                : jeibogogit@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TractorRisk class from file TractorRisk.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tractor_risk import TractorRisk
    return TractorRisk(iface)
