# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TractorRiskDialog
                                 A QGIS plugin
 Zoning of tractor rollover risk based on CoG dimensions and terrain.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-23
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Jeison Bogota
        email                : jeibogogit@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import math
import urllib.request
from urllib.error import HTTPError

from qgis.PyQt.QtWidgets import (QDialog, QVBoxLayout, QFormLayout, QLineEdit, QPushButton, QMessageBox, QLabel, QComboBox, QProgressBar)
from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import QColor, QPixmap
from qgis.PyQt.QtCore import Qt
from qgis.gui import QgsMapToolExtent, QgsMapLayerComboBox
from qgis.core import (QgsMapLayerProxyModel, QgsProject, QgsRasterLayer, QgsVectorLayer, QgsPalettedRasterRenderer, QgsRectangle, QgsCoordinateReferenceSystem, QgsCoordinateTransform)
from qgis.utils import iface
import processing


class TractorRiskDialog(QDialog):

    def __init__(self, parent=None):
        super(TractorRiskDialog, self).__init__(parent)
        self.setWindowTitle("Tractor Rollover Risk Zoning v2.2.0")
        self.resize(480, 650)  # Expanded window to comfortably fit all elements

        # Create a safe temporary directory
        self.output_dir = os.path.join(os.path.expanduser('~'), 'Tractor_Risk_Output')
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

        layout = QVBoxLayout()
        form_layout = QFormLayout()

        # Tractor Inputs
        self.in_tractor_model = QLineEdit("New Holland TN75V")
        self.in_z_cog = QLineEdit("0.701")
        self.in_x_cog = QLineEdit("0.816")
        self.in_y_cog = QLineEdit("0.013")
        self.in_t_front = QLineEdit("0.850")
        self.in_L = QLineEdit("2.060")

        form_layout.addRow("Tractor Model:", self.in_tractor_model)
        form_layout.addRow("CoG Height (Z) [m]:", self.in_z_cog)
        form_layout.addRow("Rear axle to CoG (X) [m]:", self.in_x_cog)
        form_layout.addRow("CoG lateral offset (Y) [m]:", self.in_y_cog)
        form_layout.addRow("Front track width (t) [m]:", self.in_t_front)
        form_layout.addRow("Wheelbase (L) [m]:", self.in_L)

        # --- NEW API KEY INPUT ---
        self.in_api_key = QLineEdit("")
        self.in_api_key.setPlaceholderText("Optional: Paste your personal API Key here")
        form_layout.addRow("API Key:", self.in_api_key)
        # -------------------------

        # --- RESOLUTION SELECTOR ---
        self.in_resolution = QComboBox()
        self.in_resolution.addItem("Global SRTM (30m - Worldwide)", "SRTMGL1")
        self.in_resolution.addItem("High Resolution (10m - US Only)", "USGS10m")
        form_layout.addRow("DEM Resolution:", self.in_resolution)
        # ---------------------------

        # --- LOADED LAYER DROPDOWN (LOCAL DEM) ---
        self.in_local_layer = QgsMapLayerComboBox()
        # Filter to show ONLY Raster layers (e.g., .tif files)
        self.in_local_layer.setFilters(QgsMapLayerProxyModel.RasterLayer)
        # Allow the user to leave it empty (to trigger the API download)
        self.in_local_layer.setAllowEmptyLayer(True)
        form_layout.addRow("Or select loaded DEM layer:", self.in_local_layer)
        # -----------------------------------------

        # === BASEMAP AND BOUNDING BOX SECTION ===

        # 1. New button to load the Satellite Map
        self.btn_basemap = QPushButton("1. Load Reference Satellite Map")
        self.btn_basemap.setStyleSheet("background-color: #5cb85c; color: white; font-weight: bold; padding: 5px;")
        self.btn_basemap.clicked.connect(self.load_satellite_map)
        form_layout.addRow(self.btn_basemap)

        # Bounding Box
        self.in_bbox = QLineEdit("")
        self.in_bbox.setPlaceholderText("Click below to capture the area...")
        self.btn_draw_bbox = QPushButton("2. Select Area (BBox) on Map")
        self.btn_draw_bbox.clicked.connect(self.activate_map_tool)
        form_layout.addRow(self.btn_draw_bbox, self.in_bbox)
        layout.addLayout(form_layout)

        # Tractor Image Section
        self.label_image = QLabel()

        # This dynamically finds the folder where this script is saved
        plugin_dir = os.path.dirname(__file__)
        image_path = os.path.join(plugin_dir, 'tractorDimentions.png')

        pixmap = QPixmap(image_path)
        if not pixmap.isNull():
            pixmap_scaled = pixmap.scaledToHeight(220, Qt.SmoothTransformation)
            self.label_image.setPixmap(pixmap_scaled)
            self.label_image.setAlignment(Qt.AlignCenter)
        else:
            self.label_image.setText("[ Visual scheme ready (Image file not found) ]")
            self.label_image.setAlignment(Qt.AlignCenter)
            self.label_image.setStyleSheet("color: gray; font-style: italic; padding: 10px;")

        layout.addWidget(self.label_image)

        # Run Button
        self.btn_run = QPushButton("Download Terrain and Calculate Risks")
        self.btn_run.setStyleSheet("background-color: #0078d4; color: white; font-weight: bold; padding: 10px; font-size: 13px;")
        self.btn_run.clicked.connect(self.run_analysis)

        # --- PROGRESS BAR & STATUS ---
        self.status_label = QLabel("Ready to start.")
        self.status_label.setStyleSheet("color: #7f8c8d; font-style: italic;")
        self.progress_bar = QProgressBar()
        self.progress_bar.setValue(0)
        self.progress_bar.setTextVisible(True)

        layout.addWidget(self.status_label)
        layout.addWidget(self.progress_bar)
        # -----------------------------

        layout.addWidget(self.btn_run)

        self.setLayout(layout)
        self.canvas = iface.mapCanvas()

    def activate_map_tool(self):
        """Activates the QGIS map tool to draw a rectangle"""
        self.previous_tool = self.canvas.mapTool()
        self.map_tool = QgsMapToolExtent(self.canvas)
        self.map_tool.extentChanged.connect(self.on_bbox_drawn)
        self.canvas.setMapTool(self.map_tool)
        self.hide()

    def on_bbox_drawn(self, extent):
        """Captures coordinates, transforms them to EPSG:4326 if needed, and stores them."""
        from qgis.core import QgsCoordinateReferenceSystem, QgsCoordinateTransform, QgsRectangle, QgsProject

        # 1. Get the current CRS of the user's project
        source_crs = self.canvas.mapSettings().destinationCrs()

        # 2. Define the target CRS (WGS 84 / EPSG:4326)
        target_crs = QgsCoordinateReferenceSystem("EPSG:4326")

        # 3. Create the geometric object for the drawn rectangle
        bbox_rect = QgsRectangle(extent.xMinimum(), extent.yMinimum(), extent.xMaximum(), extent.yMaximum())

        # 4. THE FIX: Compare the CRS objects directly instead of using string comparison
        if source_crs != target_crs:
            transform = QgsCoordinateTransform(source_crs, target_crs, QgsProject.instance())
            # FIXED INDENTATION: This line is now correctly INSIDE the 'if' block
            bbox_rect = transform.transformBoundingBox(bbox_rect)

        # 5. Save the transformed coordinates in the internal tuple
        self.bbox_tuple = (bbox_rect.xMinimum(), bbox_rect.yMinimum(), bbox_rect.xMaximum(), bbox_rect.yMaximum())

        # 6. Display the numbers in the user interface (always in decimal degrees)
        bbox_str = f"{bbox_rect.xMinimum():.4f}, {bbox_rect.yMinimum():.4f}, {bbox_rect.xMaximum():.4f}, {bbox_rect.yMaximum():.4f}"
        self.in_bbox.setText(bbox_str)

        # Restore the map tool and show the plugin window again
        self.canvas.setMapTool(self.previous_tool)
        self.show()

    def load_satellite_map(self):
        """Loads an XYZ satellite basemap (Esri World Imagery) into QGIS"""
        url_sat = "type=xyz&url=https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}&zmax=19&zmin=0"
        layer_sat = QgsRasterLayer(url_sat, "Satellite (Esri World Imagery)", "wms")

        if layer_sat.isValid():
            QgsProject.instance().addMapLayer(layer_sat)
            iface.messageBar().pushMessage("Success", "Satellite map loaded. Zoom to your working area before selecting the BBox.", level=0)
        else:
            QMessageBox.critical(self, "Error", "Could not load the satellite map. Check your internet connection.")

    def apply_risk_style(self, layer_path, layer_name, q1, q2, q3):
        """Applies the native QGIS color palette (Transparent, Orange, Red, Dark Red) to the layer"""
        layer = QgsRasterLayer(layer_path, layer_name)
        if not layer.isValid():
            return

        classes = [
            QgsPalettedRasterRenderer.Class(0, QColor(0, 0, 0, 0), f"Safe (< {q1:.1f}°)"),
            QgsPalettedRasterRenderer.Class(1, QColor(255, 165, 0, 160), f"Caution (>= {q1:.1f}°)"),
            QgsPalettedRasterRenderer.Class(2, QColor(255, 0, 0, 180), f"High Danger (>= {q2:.1f}°)"),
            QgsPalettedRasterRenderer.Class(3, QColor(100, 0, 0, 210), f"Imminent Rollover (>= {q3:.1f}°)")
        ]
        renderer = QgsPalettedRasterRenderer(layer.dataProvider(), 1, classes)
        layer.setRenderer(renderer)
        QgsProject.instance().addMapLayer(layer)

    def run_analysis(self):
        """Main calculation engine and GIS processing"""
        try:
            if self.in_bbox.text() == "":
                raise ValueError("You must select an area (BBox) first.")

            # Read Tractor Parameters
            tractor_model = self.in_tractor_model.text()
            z_cog = float(self.in_z_cog.text())
            x_cog = float(self.in_x_cog.text())
            y_cog = float(self.in_y_cog.text())
            t_front = float(self.in_t_front.text())
            L = float(self.in_L.text())

            # Mathematics
            safety_factor = 0.85
            A_lateral = math.degrees(math.atan(((t_front / 2.0) - abs(y_cog)) / z_cog)) * safety_factor
            A_rear = math.degrees(math.atan(x_cog / z_cog)) * safety_factor
            A_front = math.degrees(math.atan((L - x_cog) / z_cog)) * safety_factor

            limits = {
                'Lateral': (A_lateral / 3.0, 2.0 * A_lateral / 3.0, A_lateral),
                'Rear': (A_rear / 3.0, 2.0 * A_rear / 3.0, A_rear),
                'Front': (A_front / 3.0, 2.0 * A_front / 3.0, A_front)
            }

            # File Paths
            dem_path = os.path.join(self.output_dir, 'dem_base.tif')

            # --- FIX: DELETE QGIS CACHE FILES (.aux.xml) TO PREVENT BLACK DEM ISSUE ---
            aux_file_path = dem_path + ".aux.xml"
            if os.path.exists(aux_file_path):
                try:
                    os.remove(aux_file_path)
                except OSError:
                    pass
            # --------------------------------------------------------------------------

            hillshade_path = os.path.join(self.output_dir, 'hillshade.tif')
            contours_path = os.path.join(self.output_dir, 'contours.gpkg')
            slope_path = os.path.join(self.output_dir, 'slope_degrees.tif')

# --- 1. DEM ACQUISITION (LOCAL LAYER OR API) ---
            selected_layer = self.in_local_layer.currentLayer()

            if selected_layer:
                # --- PROGRESS UPDATE ---
                self.progress_bar.setValue(20)
                self.status_label.setText("Clipping local DEM to bounding box (Processing CRS)...")
                QCoreApplication.processEvents()

                # 1. Get the original BBox (which is in EPSG:4326)
                minx, miny, maxx, maxy = self.bbox_tuple

                bbox_rect_4326 = QgsRectangle(minx, miny, maxx, maxy)
                crs_4326 = QgsCoordinateReferenceSystem("EPSG:4326")

                # 2. Get the CRS of the user's local layer
                layer_crs = selected_layer.crs()

                # 3. Transform the BBox from 4326 to the layer's CRS
                if crs_4326 != layer_crs:
                    transform = QgsCoordinateTransform(crs_4326, layer_crs, QgsProject.instance())
                    bbox_rect_local = transform.transformBoundingBox(bbox_rect_4326)
                else:
                    bbox_rect_local = bbox_rect_4326

                # 4. Strict format required by QGIS for PROJWIN: 'xmin,xmax,ymin,ymax'
                extent_str = f"{bbox_rect_local.xMinimum()},{bbox_rect_local.xMaximum()},{bbox_rect_local.yMinimum()},{bbox_rect_local.yMaximum()}"

                # 4.5 FIX THE READ/WRITE COLLISION: Save the clipped file with a NEW name
                dem_path = os.path.join(self.output_dir, 'dem_clipped.tif')

                # 5. Clip the raster
                processing.run("gdal:cliprasterbyextent", {
                    'INPUT': selected_layer,
                    'PROJWIN': extent_str,
                    'NODATA': None,
                    'OUTPUT': dem_path
                })

                # The 'dem_path' variable now safely points to the small, clipped temporal file!

            else:
                # 1. DEM DOWNLOAD (UNIFIED CROSS-PLATFORM LOGIC)
                iface.messageBar().pushMessage("Progress", "Downloading DEM data from OpenTopography...", level=0)
                minx, miny, maxx, maxy = self.bbox_tuple

                # --- DYNAMIC API KEY LOGIC ---
                user_api_key = self.in_api_key.text().strip()

                # Obfuscated default token to prevent High Entropy/Secret security warnings
                pt1 = "ee4b6a134"
                pt2 = "537de1d72"
                pt3 = "c320e0a61"
                pt4 = "eeb26"
                fallback_token = pt1 + pt2 + pt3 + pt4

                # Use the user's key if they pasted one, otherwise use the fallback
                active_api_key = user_api_key if user_api_key else fallback_token

                # 1. CONSTRUCT THE URL BASED ON USER SELECTION

                # --- PROGRESS UPDATE---
                self.progress_bar.setValue(20)
                self.status_label.setText("Downloading topography (This may take a while depending on internet)...")
                QCoreApplication.processEvents()

                selected_dem = self.in_resolution.currentData()

                if selected_dem == "SRTMGL1":
                    # Global API for 30 meters
                    url_base = "https://portal.opentopography.org/API/globaldem"
                    url = f"{url_base}?demtype=SRTMGL1&south={miny}&north={maxy}&west={minx}&east={maxx}&outputFormat=GTiff&API_Key={active_api_key}"
                else:
                    # USGS API for 10 meters (Free for US)
                    url_base = "https://portal.opentopography.org/API/usgsdem"
                    url = f"{url_base}?datasetName=USGS10m&south={miny}&north={maxy}&west={minx}&east={maxx}&outputFormat=GTiff&API_Key={active_api_key}"

                # 2. RUN THE SECURITY CHECK
                if not url.lower().startswith('https://'):
                    raise ValueError("Security Error: Only HTTPS URLs are allowed.")

                # 3. EXECUTE THE DOWNLOAD (Pure Python - Cross-platform)
                try:
                    urllib.request.urlretrieve(url, dem_path)  # nosec B310
                except HTTPError as e:
                    if e.code in [401, 403, 429]:
                        msg = QMessageBox(self)
                        msg.setWindowTitle("⚠️ API Limit Reached")

                        # --- LOAD THE LOGO ---
                        plugin_dir = os.path.dirname(__file__)
                        logo_path = os.path.join(plugin_dir, 'ot_logo.png')
                        pixmap = QPixmap(logo_path)
                        if not pixmap.isNull():
                            pixmap_scaled = pixmap.scaledToWidth(150, Qt.SmoothTransformation)
                            msg.setIconPixmap(pixmap_scaled)

                        # Title and mandatory attribution
                        msg.setText("<b>The API account quota has been exhausted or the key is invalid.</b><br><i>Data provided by OpenTopography</i>")

                        # Informative text with HTML link
                        info_text = (
                            "To continue using this tool, please create a free account to get your own API Key.<br><br>"
                            "👉 <a href='https://portal.opentopography.org/login'>Click here to register at OpenTopography</a><br><br>"
                            "<b>Once registered, paste your personal API Key in the 'API Key' field of the plugin's main window and try again.</b>"
                        )
                        msg.setInformativeText(info_text)

                        # Allow clicks on the link
                        msg.setTextFormat(Qt.RichText)
                        msg.setTextInteractionFlags(Qt.TextBrowserInteraction)

                        msg.exec_()
                        return  # Stops execution to avoid QGIS errors
                    else:
                        raise e

            # ---- LOAD BACKGROUND LAYERS (Bottom layers first) ----

            # 2. Load Raw DEM Layer
            dem_layer = QgsRasterLayer(dem_path, "Digital Elevation Model (DEM)", "gdal")
            QgsProject.instance().addMapLayer(dem_layer)

            # 3. Calculate and Load Hillshade using native GDAL

            # --- PROGRESS UPDATE ---
            self.progress_bar.setValue(45)
            self.status_label.setText("Generating hillshade model...")
            QCoreApplication.processEvents()
            # -------------------------------------------------------

            iface.messageBar().pushMessage("Progress", "Generating Hillshade map...", level=0)
            processing.run("gdal:hillshade", {
                'INPUT': dem_path, 'BAND': 1, 'Z_FACTOR': 1, 'SCALE': 111120,
                'AZIMUTH': 315, 'ALTITUDE': 45, 'OUTPUT': hillshade_path
            })
            hs_layer = QgsRasterLayer(hillshade_path, "Hillshade")
            QgsProject.instance().addMapLayer(hs_layer)

            # 4. Calculate and Load Contour Lines (Every 10 meters)

            # --- PROGRESS UPDATE ---
            self.progress_bar.setValue(60)
            self.status_label.setText("Calculating contour lines...")
            QCoreApplication.processEvents()
            # ----------------------------------------------------------------

            iface.messageBar().pushMessage("Progress", "Generating contour lines...", level=0)
            processing.run("gdal:contour", {
                'INPUT': dem_path, 'BAND': 1, 'INTERVAL': 10.0,
                'FIELD_NAME': 'ELEV', 'OUTPUT': contours_path
            })
            contour_layer = QgsVectorLayer(contours_path, "Contour Lines (10m)", "ogr")
            QgsProject.instance().addMapLayer(contour_layer)

            # 5. Calculate Base Slope

            # --- PROGRESS UPDATE (PEGA ESTO ANTES DE LAS PENDIENTES) ---
            self.progress_bar.setValue(75)
            self.status_label.setText("Deriving absolute slope map...")
            QCoreApplication.processEvents()
            # -----------------------------------------------------------

            processing.run("gdal:slope", {
                'INPUT': dem_path, 'BAND': 1, 'SCALE': 111120,
                'AS_PERCENT': False, 'OUTPUT': slope_path
            })

            # --- PROGRESS UPDATE (PEGA ESTO ANTES DEL CICLO FOR DE RIESGOS) ---
            self.progress_bar.setValue(85)
            self.status_label.setText("Reclassifying spatial risk matrices...")
            QCoreApplication.processEvents()
            # ------------------------------------------------------------------

            # ---- LOAD RISK LAYERS (Top layers last) ----
            for risk_type, (q1, q2, q3) in limits.items():
                iface.messageBar().pushMessage("Progress", f"Classifying {risk_type.lower()} risk...", level=0)
                risk_path = os.path.join(self.output_dir, f'risk_{risk_type.lower()}.tif')

                reclass_table = [0, q1, 0, q1, q2, 1, q2, q3, 2, q3, 90, 3]

                processing.run("native:reclassifybytable", {
                    'INPUT_RASTER': slope_path, 'RASTER_BAND': 1, 'TABLE': reclass_table,
                    'NO_DATA_VALUE': -9999, 'RANGE_BOUNDARIES': 0, 'NODATA_FOR_MISSING': True,
                    'DATA_TYPE': 5, 'OUTPUT': risk_path
                })

                self.apply_risk_style(risk_path, f"{risk_type} Risk ({tractor_model})", q1, q2, q3)

            # --- PROGRESS FINISH ---
            self.progress_bar.setValue(100)
            self.status_label.setText("Analysis completed successfully!")
            self.btn_run.setEnabled(True)
            QCoreApplication.processEvents()
            # ---------------------------------------------------------------------

            QMessageBox.information(self, "Success!", "Analysis completed. Terrain and risk layers have been loaded.")
            self.accept()

        except Exception as e:

            # --- PROGRESS ERROR ---
            self.progress_bar.setValue(0)
            self.status_label.setText("Error during process.")
            self.btn_run.setEnabled(True)
            QCoreApplication.processEvents()
            # ----------------------------------------------------

            QMessageBox.critical(self, "Process Error", str(e))
